on: [push, pull_request]
name: Clippy/Fmt
jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }} --profile minimal --component clippy --no-self-update
          rustup default ${{ matrix.rust }}

      - name: Run cargo clippy
        run: cargo clippy --features full --tests -- -D warnings

  rustfmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust nightly with rustfmt
        run: |
          rustup toolchain install nightly --profile minimal --component rustfmt --no-self-update
          rustup default nightly

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
