on: [push, pull_request]
name: Tests

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --features full
    - name: Run tests
      run: cargo test --verbose  --features full
 
