on: [push, pull_request]
name: Tests

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.65.0

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --features full
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests full
      run: cargo test --verbose --features full
    - name: Run tests tls
      run: cargo test --verbose --features tls-native

