on: [push, pull_request]
name: Tests

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust ${{ matrix.rust }}
      run: |
        rustup toolchain install ${{ matrix.rust }} --profile minimal --no-self-update
        rustup default ${{ matrix.rust }}
    - name: Build
      run: cargo build --verbose --features full
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests full
      run: cargo test --verbose --features full
    - name: Run tests tls
      run: cargo test --verbose --features tls-native
    - name: Build http3
      run: cargo build --verbose --features http3
    - name: Run tests http3
      run: cargo test --verbose --features http3

